name: lobor
description: A new Flutter project.
publish_to:
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_localization:
  flutter_native_splash:
  intl:
  cached_network_image:
  flutter_svg:
  firebase_core: ^2.15.0
  pinput:
  smooth_page_indicator:
  carousel_slider: ^4.2.1
  provider:
  shared_preferences:
  get_it:
  internet_connection_checker:
  shimmer:


  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.7.0
  firebase_auth: ^4.7.0
  cloud_firestore: ^4.8.3
  geolocator: ^9.0.2
  geocoding:
  flutter_rating_bar:
  date_picker_timeline: ^1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:
  assets:
    - assets/
    - assets/images/
    - assets/fonts/
  uses-material-design: true
  generate: true
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  adaptive_icon_background: "#ffffff"







  fonts:
    - family: DIN Next LT W23
      fonts:
        - asset: assets/fonts/din-next-lt-w23-regular.ttf
          weight: 500
    # Add more font configurations if needed

flutter_native_splash:
  image: "assets/logo.png"
  color: "#5FD068"



  # To add assets to your application, add an assets section, like this:

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
